logicalclocks/consul-chef

- metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1679
> [HOPSWORKS-1679] pin version of java in Berksfile

- metadata.rb
> [HOPSWORKS-1679]  Add

- recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1729
> [HOPSWORKS-1729] Disable SELinux

- providers/service.rb
- resources/service.rb
https://github.com/logicalclocks/hops-testing-ee/pull/46
> [HOPSWORKS-1728] Register Logstash with Consul

- recipes/master.rb
- recipes/slave.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1726
> [HOPSWORKS-1726] call consul::default from both slave and master recipes

- recipes/default.rb
- recipes/start.rb
- templates/default/init/consul.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1785
> [HOPSWORKS-1785] Bind consul to localhost IP when doing localhost installations

- Berksfile
- metadata.rb
tests: https://github.com/logicalclocks/hops-testing-ee/pull/110
> [HOPSWORKS-1862] Fix cyclic dependency error

- libraries/default.rb
- recipes/default.rb
- recipes/install.rb
- recipes/master.rb
- recipes/security.rb
- recipes/slave.rb
- templates/default/config/master.hcl.erb
- templates/default/config/slave.hcl.erb
- templates/default/init/systemd_env_vars.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657
> [HOPSWORKS-1657] System users x.509 v2

- recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1915
> [HOPSWORKS-1915] Not modifiable extended attribute for /etc/resolv.conf

- recipes/default.rb
tests: https://github.com/logicalclocks/hops-testing-ee/pull/127
> [HOPSWORKS-1902] Add support for managed kubernetes

- recipes/security.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1977
> [HOPSWORKS-1977] Replace kagent/test with kagent/enabled

- templates/default/init/consul.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
> [HOPSWORKS-2065] Limit number of allowed restarts after a failure

- templates/default/init/consul.service.erb
* [HOPSWORKS-2065] Limit number of allowed restarts after a failure
* [HOPSWORKS-2065] Wait before each restart
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
> [HOPSWORKS-2065] Limit number of allowed restarts after a failure (#21)

- recipes/security.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2241
> [HOPSWORKS-2241] Get Hopsworks private IP only if needed

- files/default/domain_utils.sh
- recipes/default.rb
Fixes https://logicalclocks.atlassian.net/browse/HOPSWORKS-2800
> [HOPSWORKS-2800] Add utility function to check if a service is ready

- recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2820
> [HOPSWORKS-2820] Remove any extended attributes from resolv.conf before editing it and persist any existing dns configuration

- attributes/default.rb
- metadata.rb
- templates/default/init/consul.service.erb
Resolves https://logicalclocks.atlassian.net/browse/HOPSWORKS-3014
> [HOPSWORKS-3014] Expose attribute to configure client facing APIs bind address

- templates/default/retryable_health_check.sh.erb
Fixes https://hopsworks.atlassian.net/browse/HWORKS-168
> [HWORKS-168] Override error exit code

- recipes/default.rb
https://hopsworks.atlassian.net/browse/HWORKS-175
> [HWORKS-175] Do not modify resolvers if flag is set

- recipes/default.rb
https://hopsworks.atlassian.net/browse/HWORKS-203
> [HWORKS-203] Explicitly enable dnsmasq systemd, CentOS does not do it

- recipes/default.rb
https://hopsworks.atlassian.net/browse/HWORKS-268
> [HWORKS-268] Retry to install dnsmasq in case it fails

- templates/default/init/consul.service.erb
https://hopsworks.atlassian.net/browse/CLOUD-419
> [CLOUD-419] Add service lookup target as dependency to consul

- attributes/default.rb
- metadata.rb
- recipes/default.rb
https://hopsworks.atlassian.net/browse/CLOUD-418
> [CLOUD-418] Configure systemd to restart dnsmasq in case of failure

- attributes/default.rb
https://hopsworks.atlassian.net/browse/CLOUD-608
> [CLOUD-608] Bind client APIs to both private IPs and loopback

- attributes/default.rb
- recipes/default.rb
- recipes/install.rb
- templates/default/config/master.hcl.erb
- templates/default/config/slave.hcl.erb
- templates/default/dnsmasq-conf.erb
- templates/default/init/consul.service.erb
https://hopsworks.atlassian.net/browse/HWORKS-649
> [HWORKS-649] Use log files for Consul and dnsmasq instead of stdout/systemd

- attributes/default.rb
- metadata.rb
- templates/default/config/master.hcl.erb
- templates/default/config/slave.hcl.erb
https://hopsworks.atlassian.net/browse/HWORKS-832
> [HWORKS-832] Set size limit in consul log files
